title: API Panda
description: API Panda Docs
theme: just-the-docs

url: https://just-the-docs.github.io

nav_external_links:
  - title: Demo App
    url: https://demo.apipanda.net/
    hide_icon: false
    opens_in_new_tab: true
  - title: Swagger doc
    url: https://app.apipanda.net/swagger/index.html
    hide_icon: false
    opens_in_new_tab: true
